### ISSUE TITLE
The bootstrapped TFCE scores for F-contrasts do not seem correctly computed

### ISSUE THREAD

**Issue by BryanGuillaume** [NISOx-BDI/SwE-toolbox#112]
In `swe_cp_wb`, the original tfce score for an F-contrast is computed by first converting the original parametric -log10(p-values) into equivalent Z-scores and then use these equivalent Z-scores as input in `swe_tfce_transform`:

 ```
% Convert F statistics to Z scores.
      scorevol=-swe_invNcdf(10.^(-spm_read_vols(VlP)));
      scorevol(isnan(scorevol))=0;
          
      % Convert to TFCE.
      par_tfce = swe_tfce_transform(scorevol, H, E, C, dh);
```

This seems necessary as `swe_tfce_transform` appears to work with Z-scores as input as is indicated in the help of the function:

`% This function calculates the TFCE statistical from a Z statistic image.`

The **issue** seems to appear for the bootstrap tfce scores where, I believe, the input in `swe_tfce_transform` are not equivalent Z-scores but equivalent X-scores that are obtained through the function `swe_hyptest`. Here are the relevant piece of code:

### Computation of the bootstraped TFCE score
```
     % Calculate TFCE uncorrected p image.
      if TFCE
	% Obtain P values.
	hyptest=swe_hyptest(SwE, score, blksz, cCovBc, Cov_vis, dofMat);
	
	% Current XYZ indices
	currXYZ = XYZ(1:3, index);
	  
	  % T stat from this bootstrap
	  scorevol(sub2ind(DIM,currXYZ(1,:),currXYZ(2,:),currXYZ(3,:))) = hyptest.positive.conScore;
	
      end
      
    end % (bch)
    
    if TFCE

      if SwE.WB.stat == 'T'        
	
	% Bootstrapped tfce vol.
	tfce = swe_tfce_transform(scorevol,H,E,C,dh);
	tfce_neg = swe_tfce_transform(-scorevol,H,E,C,dh);    
        
      else
	
	% Bootstrapped tfce vol.
	tfce = swe_tfce_transform(scorevol,H,E,C,dh);
	
      end
```
### Computation of hyptest.positive.conScore in 
```
% Calculate converted score in a way which minimizes under/overflow
if (SwE.WB.stat == 'T')
    
    ....

else
    conScore = spm_invXcdf(negp, 1);
end
```

As it seems that `swe_tfce_transform` works only with Z-scores (@nicholst Is it actually true?), I am suggesting to compute the equivalent Z-scores like it is done for the orginal tfce scores and feed them to swe_tfce_transform as input instead of the equivalent X-scores.

@nicholst: As I am not familiar with TFCE, can you please confirm that I understand well how the code works and if the proposed solution above is appropriate?

**Comment by nicholst** [comment]
This does look funny... indeed, input to TFCE needs to be a variable that behaves like a T/Z (mean 0, variance 1). 

@TomMaullin - do you have any recollection of this? It was my dim memory that X values were to be transformed to Z before feeding into TFCE... yes?

**Comment by TomMaullin** [comment]
Apologies, yes I believe you are right @BryanGuillaume. I can confirm `swe_tfce_transform` should be taking in an equivalent Z score map. 

My logic for this section of code was to only have `scorevol` derived from `conScore` (assigned on [line 1733 of swe_cp_WB.m](https://github.com/NISOx-BDI/SwE-toolbox/blob/master/swe_cp_WB.m#L1733) ), which I originally intended to be the `Z` value map for the hypothesis test (derived from `T` or `F`), but you are right `conScore` is actually an `X` rather than `Z` for an `F` statistic. I am unsure if it has always been this way but this does need fixing.

As the `conScore` field is now used elsewhere I would suggest not changing this but instead replacing [line 1733 of swe_cp_WB.m](https://github.com/NISOx-BDI/SwE-toolbox/blob/master/swe_cp_WB.m#L1733) with something like what is given on [lines 1077-1079](https://github.com/NISOx-BDI/SwE-toolbox/blob/master/swe_cp_WB.m#L1077-L1079).  i.e. replace;

```
scorevol(sub2ind(DIM,currXYZ(1,:),currXYZ(2,:),currXYZ(3,:))) = hyptest.positive.conScore;
```

With something like:

```
# T test already converted to Z
if strcmp(WB.stat, 'T'):
    scorevol(sub2ind(DIM,currXYZ(1,:),currXYZ(2,:),currXYZ(3,:))) = hyptest.positive.conScore;
# F test needs to be converted to Z
else:
    # Get score volume from p values
    sv=-swe_invNcdf(10.^(-spm_read_vols(hyptest.positive.p)));
    # remove NaNs
    sv(isnan(scorevol))=0;
    # Save as scorevol
    scorevol(sub2ind(DIM,currXYZ(1,:),currXYZ(2,:),currXYZ(3,:))) = sv
```

Or something along those lines...

I must admit I felt for a long time something felt odd with the TFCE F output here but spent a lot of time going over and over the code and could not find any error - thanks for putting me out of my misery and spotting this! Please don't hesitate to tag/ask me anything in future if you need by the way.

**Comment by BryanGuillaume** [comment]
Thanks both for your feedback on this. That is very helpful. I will edit the code today using the suggested piece of code by @TomMaullin . That should fix the issue.

**Comment by BryanGuillaume** [comment]
This issue has been adressed in PR #113
