### ISSUE TITLE
It's time to make a new SwE release!

### ISSUE THREAD

**Issue by nicholst** [NISOx-BDI/SwE-toolbox#36]
Last release was in April and the new GUI for WB (and the footer) are great features that people should get to use.

@TomMaullin can you clone the "HOWTO" Camille created for SnPM?

Now, I realise there is quite a bit to do for that.  You'll have to create a Zenodo page... more stuff?  

*So* if you are about to leave for holiday, and there isn't time to create the HOWTO and all that, then could you *just* create a release (after merging two open PR's) and let me know, and then we can fire off a quick email to users.

**Comment by TomMaullin** [comment]
Hi @nicholst , 

I have cloned the HOWTO, which can be found [here](https://github.com/NISOx-BDI/SwE-toolbox/wiki), and prepared a PR for the new release, PR #38 , as @cmaumet 's SnPM notes suggest. (Note: This includes the changes made in PR #34 so this must first be merged before this release). 

I'm not sure exactly what should be done with Zenodo - I haven't used this before - but am happy to give it a try over the next 3 days if someone can point me in the right direction. Otherwise, I can just make this release without Zenodo.

**Comment by nicholst** [comment]
Let's not worry about Zenodo. Just open an issue so we don't forget to do
it later.
-- 
_________________________________________________________
Thomas Nichols, PhD
Professor of Neuroimaging Statistics
Nuffield Department of Population Health | University of Oxford
Big Data Institute | Li Ka Shing Centre for Health Information and Discovery
Old Road Campus | Headington | Oxford | OX3 7LF | United Kingdom
T: +44 1865 743590 | E: thomas.nichols@bdi.ox.ac.uk
W: http://nisox.org | http://www.bdi.ox.ac.uk

**Comment by TomMaullin** [comment]
Apologies for the delay. Version 1.2.9 of the SwE toolbox has now been released [here](https://github.com/NISOx-BDI/SwE-toolbox/releases/tag/v1.2.9).
