### ISSUE TITLE
Main GUI window sizing

### ISSUE THREAD

**Issue by justbennet** [NISOx-BDI/SwE-toolbox#71]
With the latest version, the main GUI window sizes such that it truncates the two top lines, which give the toolbox name and the version number.

![swe-gui](https://user-images.githubusercontent.com/1595586/47438953-73e1e980-d779-11e8-8385-bb4194bad491.png)

My screen resolution is 1400x1024 running Matlab R2018a on Ubuntu 16.04.  That should make the position parameters 500, 372, 300, 290.

I changed them to

```
'Position',[S(3)/2-200,S(4)/2-140,400,290],...
```

and that made it look like this.

![new-sw-gui](https://user-images.githubusercontent.com/1595586/47439888-29fa0300-d77b-11e8-8015-429add3307b0.png)

I am not sure whether the text alignment is as you would like with the new size, so I was reluctant to submit a PR without first mentioning the issue.

**Comment by justbennet** [comment]
Ah, Sorry,

```
bennet@mistakenhat:/usr/local/matlab/SwE-toolbox$ git branch
* master
bennet@mistakenhat:/usr/local/matlab/SwE-toolbox$ git show | head -1
commit 145378eff0a08604c0b4e0c20b9d15aed4933e79
```

**Comment by nicholst** [comment]
@justbennet Getting the GUI to look consistent across platforms is a nightmare.  The SPM approach on this is to set all fonts and font sizes through a wrapper function spm_platform.m.  But I do realise that we weren't consistently calling these functions and so I've made some fixes.

I've made several changes to `swe_ui_main.m` that hopefully will improve your experience.  Do you want to try it and see how it goes?  I've opened a PR #73 or just grab the file: https://raw.githubusercontent.com/nicholst/SwE-toolbox/FontTweak/swe_ui_main.m

Let me know how it looks.  Ideally, if it doesn't work for you, you might be having other problems with SPM fonts and you can make changes to spm.m and/or spm_platform.m so that everything looks good on your system.

**Comment by justbennet** [comment]
Thank you.  I'll give this a go and let you know.

Yes, cross-platform GUI development is a total nightmare; Java did _not_
solve that problem at all.  Even within Matlab, different versions handle
things differently.

**Comment by justbennet** [comment]
I gave your change a try.  It is much better, at least on my Linux desktop.

![new-swe-main-menu](https://user-images.githubusercontent.com/1595586/47617324-69d32a00-da9c-11e8-9082-fa99e6d35968.png)

Looks like just a touch wider, and it will be there.  I tried this using a Windows VM, and it looks quite nice there.

![new-swe-main-menu](https://user-images.githubusercontent.com/1595586/47617659-c8e66e00-da9f-11e8-9691-2fb6daeae75b.png)

**Comment by nicholst** [comment]
Tagging @gllmflndn in case he has any ideas on this Linux font issue.

**Comment by nicholst** [comment]
@justbennet This command might help you diagnose your Matlab font woes:
```matlab
listfonts
```
Your goal is to find ones that match these four `spm_platform.m`:
```matlab
    case {'GLNX86','GLNXA64'}
        PLATFORM.font.helvetica = 'Helvetica';
        PLATFORM.font.times     = 'Times';
        PLATFORM.font.courier   = 'Courier';
        PLATFORM.font.symbol    = 'Symbol';
```

**Comment by justbennet** [comment]
Ah, good eye!  OK.  Let me see what I can do.

Sorry to be a bother.

**Comment by nicholst** [comment]
Closing for now... reopen if it continues to be a problem.
